import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("products/malibu-professional-spray-1l", "routes/product.tsx"),
  route("articles", "routes/articles.tsx"),
  route("tools/spray-tan-profit-calculator", "routes/tools.spray-tan-profit-calculator.tsx"),
  route("articles/:slug", "routes/article.tsx"),
  route("api/article-view", "routes/api.article-view.ts"),
  route("q/:code", "routes/qr-redirect.ts"),
  route("sitemap.xml", "routes/sitemap.ts"),
  route("rss.xml", "routes/rss.ts"),
  route("admin/login", "routes/admin.login.tsx"),
  route("admin/logout", "routes/admin.logout.tsx"),
  route("admin/qr-assets/:qrId/:format", "routes/admin.qr-code-image.ts"),
  route("admin", "routes/admin.layout.tsx", [
    index("routes/admin.index.tsx"),
    route("articles", "routes/admin.articles.tsx"),
    route("articles/:articleId", "routes/admin.article-editor.tsx"),
    route("article-stats", "routes/admin.article-stats.tsx"),
    route("media", "routes/admin.media.tsx"),
    route("qr-codes", "routes/admin.qr-codes.tsx"),
    route("resellers", "routes/admin.resellers.tsx"),
    route("applications/:applicationId", "routes/admin.application-detail.tsx"),
    route("accounts", "routes/admin.accounts.tsx"),
    route("accounts/:resellerId", "routes/admin.account-detail.tsx"),
    route("orders", "routes/admin.orders.tsx"),
    route("orders/:orderId", "routes/admin.order-detail.tsx"),
    route("invoices", "routes/admin.invoices.tsx"),
    route("invoices/:invoiceId", "routes/admin.invoice-detail.tsx"),
    route("invoices/:invoiceId/document", "routes/admin.invoice-document.tsx"),
    route("invoice-settings", "routes/admin.invoice-settings.tsx"),
  ]),
  route("portal/login", "routes/portal.login.tsx"),
  route("portal/register", "routes/portal.register.tsx"),
  route("portal/logout", "routes/portal.logout.tsx"),
  route("portal", "routes/portal.layout.tsx", [
    index("routes/portal.index.tsx"),
    route("order", "routes/portal.order.tsx"),
  ]),
] satisfies RouteConfig;
